export const SET_SESSION_TOKEN = 'session/SET_SESSION_TOKEN'
export const SET_SESSION_STATUS = 'session/SET_SESSION_STATUS'
export const SET_BRANCH = 'session/SET_BRANCH'
export const SET_EMPLOYEE_LIST = 'session/SET_EMPLOYEE_LIST'
export const SET_CUSTOMER_LIST = 'session/SET_CUSTOMER_LIST'
export const SET_ERROR = 'session/SET_ERROR'
